schema = 3

[mod]
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.1.1"
    hash = "sha256-6AbVa1URv04zlxUZA/Wc484EzrzgAuPcuub3WFBRWDc="
  [mod."github.com/aymerick/douceur"]
    version = "v0.2.0"
    hash = "sha256-NiBX8EfOvLXNiK3pJaZX4N73YgfzdrzRXdiBFe3X3sE="
  [mod."github.com/badoux/checkmail"]
    version = "v0.0.0-20170203135005-d0a759655d62"
    hash = "sha256-nIBU7wnzh+o/B2Yx3uh/7P1byuYL9C9Xmkh6TFMTmEA="
  [mod."github.com/beevik/etree"]
    version = "v1.1.0"
    hash = "sha256-tvvc/RbFjTppdAKs1xUnMhfTXiW4Yr4CQ9NmrhF8uIk="
  [mod."github.com/coreos/go-oidc/v3"]
    version = "v3.0.0"
    hash = "sha256-FG+lwSpJzsYdU0uKjuxtSqnmV0kSUxAka/8DAJqUf1k="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/didip/tollbooth/v5"]
    version = "v5.1.1"
    hash = "sha256-0FSI+ZWwH0Lr1TbHk6TMpcbdXT9Z8VZ3a0Ipi/HtUBE="
  [mod."github.com/fatih/color"]
    version = "v1.10.0"
    hash = "sha256-8iRHT86JzKRgxVG+Ip9b+0JyCgd5ZAL5UIAqkWI1Vmg="
  [mod."github.com/fatih/structs"]
    version = "v1.1.0"
    hash = "sha256-OCmubTLF1anwNnkvFZDYHnF6hFlX0WDoe/9+dDlaMPM="
  [mod."github.com/go-chi/chi"]
    version = "v4.0.2+incompatible"
    hash = "sha256-iPBX33fAci7W9O0MZJkcTLb4jBNDulMv3uk6uMO+txo="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.5.0"
    hash = "sha256-DDpwoQ/rAo3Eml3IZYZBu/2ohtGsAPBnxQsuZiKV4BU="
  [mod."github.com/gobuffalo/envy"]
    version = "v1.9.0"
    hash = "sha256-A0nd26XqYRW33EV9NMrNKoFdD+JAbLiEV+X0lKFzmuc="
  [mod."github.com/gobuffalo/fizz"]
    version = "v1.13.0"
    hash = "sha256-trrFbEL/o6eMlb0oZ/HDXmz6tEtJl4tO5ZoV+u0mip4="
  [mod."github.com/gobuffalo/flect"]
    version = "v0.2.2"
    hash = "sha256-V0ehg1hVJDikwJMRIfWCCHY/acdCeyJ3M9aDAnY8SUY="
  [mod."github.com/gobuffalo/github_flavored_markdown"]
    version = "v1.1.0"
    hash = "sha256-N8n5wSX8p//TxNIc8WahOXmY6TeYtik8cM985aNnWBk="
  [mod."github.com/gobuffalo/helpers"]
    version = "v0.6.1"
    hash = "sha256-oi9ZLWSSkZd3tVZe+5h3/xXaOLOJIHxbdspZYr+E96U="
  [mod."github.com/gobuffalo/nulls"]
    version = "v0.4.0"
    hash = "sha256-pCnxcAoPuSoA8/gru6eGB86UEXyqYVWLffOpnyUgQE0="
  [mod."github.com/gobuffalo/packd"]
    version = "v1.0.0"
    hash = "sha256-A437ph6No+N0kgyRAiqi6EON/v2Ea9jflvFmBECknH4="
  [mod."github.com/gobuffalo/packr/v2"]
    version = "v2.8.1"
    hash = "sha256-7DCanQ07tDjQ0Kf4luNQQjxuYSMGC4MSjy9pVReePcE="
  [mod."github.com/gobuffalo/plush/v4"]
    version = "v4.1.0"
    hash = "sha256-GaoO3pxZ4/Myxnjxrf8szYG39+3JuYprr846FzH+wUw="
  [mod."github.com/gobuffalo/pop/v5"]
    version = "v5.3.3"
    hash = "sha256-TK+b9g9Mi8yv+AcRoCRetwA9nXh4O3oO10M+W/+OmJ0="
  [mod."github.com/gobuffalo/tags/v3"]
    version = "v3.1.0"
    hash = "sha256-TtQtfzqSgm6vTtYhJX4VekeiFyAagWuMOP6rkurbA/U="
  [mod."github.com/gobuffalo/validate/v3"]
    version = "v3.3.0"
    hash = "sha256-NN3eHgYi3wRgCz96sTsrMyfl+MaIdr56yzI6uEXLcYM="
  [mod."github.com/gobwas/glob"]
    version = "v0.2.3"
    hash = "sha256-hYHMUdwxVkMOjSKjR7UWO0D0juHdI4wL8JEy5plu/Jc="
  [mod."github.com/gofrs/uuid"]
    version = "v4.0.0+incompatible"
    hash = "sha256-LM2nBpmCAp32ihzuUx2xec3/6zLlvBWx8vJIxGX5YS8="
  [mod."github.com/golang-jwt/jwt"]
    version = "v3.2.1+incompatible"
    hash = "sha256-lRqMYMddv9J5IwqDBjqGmFtLpwwgvq86CkCvJxzM1cw="
  [mod."github.com/golang/protobuf"]
    version = "v1.4.2"
    hash = "sha256-zhA1d1Kw1ZV/kDBZ4Iv5miKHjZBhcV8m3BiD1qocJqw="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.2"
    hash = "sha256-BRyxX3Sd/ZsxCd0KB1tPFyvmhc+jH1cTFThVGQLxkGE="
  [mod."github.com/gorilla/context"]
    version = "v1.1.1"
    hash = "sha256-pA7z/VCUIHuoP4wOeeJx+tLUFx7G8HQBjK6yfZCF5A4="
  [mod."github.com/gorilla/css"]
    version = "v1.0.0"
    hash = "sha256-Mmt/IqHpgrtWpbr/AKcJyf/USQTqEuv1HVivY4eHzoQ="
  [mod."github.com/gorilla/securecookie"]
    version = "v1.1.1"
    hash = "sha256-IBBYWfdOuXvQsb01DaA8tBizCfAE1J2KLXIn3W+NeJk="
  [mod."github.com/gorilla/sessions"]
    version = "v1.1.1"
    hash = "sha256-UGQ3lSuV1OtafiVih45k5FAxqD/TuwJWlJt2d+C9MP8="
  [mod."github.com/imdario/mergo"]
    version = "v0.0.0-20160216103600-3e95a51e0639"
    hash = "sha256-91BL+oRHWnJGjhbTpNIgeDZsHvIMNK3DSxc4vTUtzeI="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.0"
    hash = "sha256-ogTuLrV40FwS4ueo4hh6hi1wPywOI+LyIqfNjsibwNY="
  [mod."github.com/jackc/chunkreader/v2"]
    version = "v2.0.1"
    hash = "sha256-LNAEmbsxWOVPtcQ1fE1JC1yTaqyvZGa/k4zocWFBRTo="
  [mod."github.com/jackc/pgconn"]
    version = "v1.8.0"
    hash = "sha256-f6tbVNYG53Zo+AjrvxR0C6r4VMORw8zFNDMhgcBBURY="
  [mod."github.com/jackc/pgerrcode"]
    version = "v0.0.0-20201024163028-a0d42d470451"
    hash = "sha256-r2yka7PM4lYnyaP4K4IXPikvmlvRnJLFM6e3zUeE/GY="
  [mod."github.com/jackc/pgio"]
    version = "v1.0.0"
    hash = "sha256-4W0PGZlkbBZcSJmPyXi9v1gAJIK9ujVLlcbxEOx9J1A="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgproto3/v2"]
    version = "v2.0.7"
    hash = "sha256-uNqWxfQPC8QRBciiBr06fJOiP7FrFTf2AxBIpgtIaek="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20200714003250-2b9c44734f2b"
    hash = "sha256-sNfMMlmdlb5P4a4EgIHaHOcHD9N6IflYHjWj0hSI640="
  [mod."github.com/jackc/pgtype"]
    version = "v1.6.2"
    hash = "sha256-p7eI8RxbV+EvAfZOZ4PQRKJsORj7BtEkPjmguxth23w="
  [mod."github.com/jackc/pgx/v4"]
    version = "v4.10.1"
    hash = "sha256-NpxUZjnN1EiOCJsXThm9xOqJaEEXnZpD+AZFuG1nqvI="
  [mod."github.com/jmoiron/sqlx"]
    version = "v1.3.1"
    hash = "sha256-qRiJ11jKwXSQxl7M41LvqMUlGe87ktd5jzrSVFjIvuk="
  [mod."github.com/joho/godotenv"]
    version = "v1.3.0"
    hash = "sha256-Vd43lAoKpbEeunlMySqf/TrfUckcxcHIk6YPdoGLKGY="
  [mod."github.com/jonboulle/clockwork"]
    version = "v0.2.2"
    hash = "sha256-ryvMsRMd1CeuYyyLTfGRWb36AbZyxtomPBEB7hzrrqE="
  [mod."github.com/kballard/go-shellquote"]
    version = "v0.0.0-20180428030007-95032a82bc51"
    hash = "sha256-AOEdKETBMUC39ln6jBJ9NYdJWp++jV5lSbjNqG3dV+c="
  [mod."github.com/kelseyhightower/envconfig"]
    version = "v1.4.0"
    hash = "sha256-SeLQlQXYAwCbFi/TIF3wpd0v+aB689PWI+njK20Z66g="
  [mod."github.com/lestrrat-go/jwx"]
    version = "v0.9.0"
    hash = "sha256-Wo9Y7Fs9m/zmCDiAXu84IlLATaOGQlyuucLWuXj6Gi4="
  [mod."github.com/lib/pq"]
    version = "v1.9.0"
    hash = "sha256-DlaDw/xbXGEgFXzKRGeW22soA5aucvjgdHlrHgJvPE0="
  [mod."github.com/luna-duclos/instrumentedsql"]
    version = "v1.1.3"
    hash = "sha256-HzIX5mADt6Xf0lPnGY4MTrsbZ1S0eEHJrb25GBdTBYY="
  [mod."github.com/mattermost/xml-roundtrip-validator"]
    version = "v0.1.0"
    hash = "sha256-b5lspAL/mbHzYJmgHOSztGCDvqwhiVyk/c6DX9aWcQg="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.8"
    hash = "sha256-TBXc2n5tRebabjt0HipS8wCdRml0kM0JjpppUbdx1XQ="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.12"
    hash = "sha256-noBpx3K4sa7tJcPpSUh+h7wJ8CRfrObaraKC2dE6VWU="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v2.0.3+incompatible"
    hash = "sha256-+zdGqThUb7if9JAiO+6s6KXBeuT322JhfcityvdrxD4="
  [mod."github.com/microcosm-cc/bluemonday"]
    version = "v1.0.16"
    hash = "sha256-2omWo2723mDenFui5iQAuTy3NfBegv2RVBgSL+R8CzA="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.1.2"
    hash = "sha256-OU9HZYHtl0qaqMFd84w7snkkRuRY6UMSsfCnL5HYdw0="
  [mod."github.com/mrjones/oauth"]
    version = "v0.0.0-20190623134757-126b35219450"
    hash = "sha256-nHhQ8lhmPOx+vZBpWAHx0ddD7aDfAUYNF/yhVbOPmKU="
  [mod."github.com/netlify/mailme"]
    version = "v1.1.1"
    hash = "sha256-jyDKf1MhRlq30kF4EiW+po+jTS/GpKXErUicwMJpa8I="
  [mod."github.com/netlify/netlify-commons"]
    version = "v0.32.0"
    hash = "sha256-eJxbY63G3sd1Bbw5QsaVAXexinxfOqWi9C1qlAou0Ng="
  [mod."github.com/opentracing/opentracing-go"]
    version = "v1.1.0"
    hash = "sha256-7j8mpJ3kleYHxC9c1n33KTkP7EMfFkFLDE//IOpiSSo="
  [mod."github.com/patrickmn/go-cache"]
    version = "v2.1.0+incompatible"
    hash = "sha256-+i3/Cd9byb1q926jszLjadiUMUeux0VyGKnmP20EAoA="
  [mod."github.com/philhofer/fwd"]
    version = "v1.0.0"
    hash = "sha256-4oFx2fZAPhdnv+rCs/8UfJOy3GtaauQF2enApuAk6N0="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.8.0"
    hash = "sha256-ze+/FkW3z3b+frAksjWPjDolP1UtSf6z0By6PGXTirM="
  [mod."github.com/rs/cors"]
    version = "v1.6.0"
    hash = "sha256-uZGkVBiG99mmNHfiSJK9sw02f4K2Bo178Il2IzMaSIo="
  [mod."github.com/russellhaering/gosaml2"]
    version = "v0.6.1-0.20210916051624-757d23f1bc28"
    hash = "sha256-Y11GDkatTGxhRvAySvsC7GLAG/9hk9XiOpQikPOHwsQ="
  [mod."github.com/russellhaering/goxmldsig"]
    version = "v1.1.1"
    hash = "sha256-gQFi7orWpsMJxPOT3g9E5hvKejiyDGQPv4Ko/+Cgh88="
  [mod."github.com/sebest/xff"]
    version = "v0.0.0-20160910043805-6c115e0ffa35"
    hash = "sha256-kHR5DupeZzDYGyW66VaV/c2TcUuMkRPf7xscxCpqIVA="
  [mod."github.com/sergi/go-diff"]
    version = "v1.1.0"
    hash = "sha256-8NJMabldpf40uwQN20T6QXx5KORDibCBJL02KD661xY="
  [mod."github.com/sethvargo/go-password"]
    version = "v0.2.0"
    hash = "sha256-hX4nVQhBlioEHiadvdWm9Ec0tZXnW8mMXyC3UzlMojE="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.7.0"
    hash = "sha256-VClDP4DJDdMFTMGWR7I8L4hQRMU7cOphLRyUfxCvnNY="
  [mod."github.com/sourcegraph/annotate"]
    version = "v0.0.0-20160123013949-f4cad6c6324d"
    hash = "sha256-bsu85jFOThQa5/6EDKdz0R3/9AiirXwxGR/sjltXJoI="
  [mod."github.com/sourcegraph/syntaxhighlight"]
    version = "v0.0.0-20170531221838-bd320f5d308e"
    hash = "sha256-HWnE9MHUdI4CoM1DTgkiKwqez3jLYCvPHcZtnZfFYGQ="
  [mod."github.com/spf13/cobra"]
    version = "v1.1.3"
    hash = "sha256-A/1637AERYTAHP5aEDDYYCouFKAgF26Uz6ufMaWW39I="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stretchr/objx"]
    version = "v0.2.0"
    hash = "sha256-fx9mfz6FjbV2YtLQzk7Wzd+saejwoad2scLLC7Apvnw="
  [mod."github.com/stretchr/testify"]
    version = "v1.6.1"
    hash = "sha256-GwrZr9lU8698GFal0l/sFQ/TYP/eQIeNnnYJWpe3/IE="
  [mod."github.com/tinylib/msgp"]
    version = "v1.1.0"
    hash = "sha256-x3xo7aXWPAMXWwSH9TEzWmHLS0P7NWB439nWXJbHsIQ="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20201221181555-eec23a3978ad"
    hash = "sha256-eSzMOS6DWaPOp6/Ht0QAwXHIJ0Ty0OihGmifXuE2jqE="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220121210141-e204ce36a2ba"
    hash = "sha256-5a4zHy3VuSjDRwrKSACFtsIKA8X9idQ7iDMlkh7Flxg="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20200902213428-5d25da1a8d43"
    hash = "sha256-duDveniPh1UKCXYcFVpmHwDwK60i2Pcc6XYvqLtGXZI="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20201207232520-09787c993a3a"
    hash = "sha256-Phh5d0Ba21YQXkkdw4JjArr3UJa5V04P83NKmyKvZNs="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20211216021012-1d35b9e2eb4e"
    hash = "sha256-q9nSttSlJMZ9rggzT0YwuWWdWrqtpU08eOCt3mcM27Y="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20200416051211-89c76fbcd5d1"
    hash = "sha256-M1Aa8aDPlG8sH4hw+hwmpX5yFHPxfVNQxeNrrfffQ/4="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20200804184101-5ec99f83aff1"
    hash = "sha256-62f++IO8Ia32CYy+xX8XDxCcT9r1sbPvVwoKV99gf7U="
  [mod."google.golang.org/appengine"]
    version = "v1.6.6"
    hash = "sha256-nZnEfsXy3mgzRnlyWGHJKqsosvnAQFkhVszw3DSFe6Y="
  [mod."google.golang.org/protobuf"]
    version = "v1.25.0"
    hash = "sha256-3sf57K5A0nmA1UmDe+6FUNJI6UR+SfVyZWNv+2TGHT4="
  [mod."gopkg.in/DataDog/dd-trace-go.v1"]
    version = "v1.12.1"
    hash = "sha256-4w5ESI3C+cseRhdkKSo6yvw1DwnU6E0UcSJ1VT64cQA="
  [mod."gopkg.in/alexcesaro/quotedprintable.v3"]
    version = "v3.0.0-20150716171945-2caba252f4dc"
    hash = "sha256-6cgI1fteSkqNYkNeReaHz0El7hbomNiRyueg44BHI7o="
  [mod."gopkg.in/gomail.v2"]
    version = "v2.0.0-20160411212932-81ebce5c23df"
    hash = "sha256-rCKRESTIHR6dkn4HEx6ZlxHfqLTmJvIAtjQFXXaevn0="
  [mod."gopkg.in/square/go-jose.v2"]
    version = "v2.5.1"
    hash = "sha256-lqj+3lvCQi0O+fKg/q/QXS68Jk9FWB/9lHZ7X1ZdEHw="
  [mod."gopkg.in/yaml.v1"]
    version = "v1.0.0-20140924161607-9f9df34309c0"
    hash = "sha256-9Z0HKi2YmBt+ShoSjBE3bXhcZmQ+8gEw6knhrw0ZDeU="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.0"
    hash = "sha256-XWfvIV7+KXlZV4sBZd0srGeuQonS9cTYptCc6NcgVvc="
